### ISSUE TITLE
`ed/idlparsed/html.json` has no parsed IDL content

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webref#462]
`ed/idl/html.idl` seems complete and parseable by webidl2.js

**Comment by dontcallmedom** [comment]
`streams.json` which, like HTML, was recently updated to use the `Exposed=*` construction is also empty, so this is probably related.

**Comment by dontcallmedom** [comment]
running reffy `generate-idlparsed.js` manually with some logging shows the following stack trace:
```TypeError: Cannot read property 'map' of null
    at parseInterfaceOrDictionary (/home/dom/github.com/reffy/src/cli/parse-webidl.js:265:57)
    at /home/dom/github.com/reffy/src/cli/parse-webidl.js:158:13
```
which is indeed where the `Exposed` extended attribute is processed.

(meanwhile `generate-idlparsed.js` is supposed to document the errors it generates in its output, but that isn't working here - maybe because the exception is not JSON serializable by default?)

**Comment by dontcallmedom** [comment]
`Exposed=*` makes `*` a type of `rhs` rather than a value apparently, so this needs special casing `parse-webidl.js`

**Comment by dontcallmedom** [comment]
the latest run with the updated reffy  fixed this
